### ISSUE TITLE
Add configuration for adding prelude comments to output

### ISSUE THREAD

**Issue by havardh** [havardh/javaflow#31]
This issue is motivated by the need to insert `/* eslint-disable no-use-before-define */`.
This rule is violated as the types are sorted in the output.

**Comment by relekang** [comment]
Maybe also have a default comment something like:

```
/*
 * This file is generated by https://github.com/havardh/javaflow.
 * Any changes to this file will probably be overwritten by javaflow.
 */
```

**Comment by havardh** [comment]
Resolved by the comment prefixer
