### ISSUE TITLE
Annotation for nullable field

### ISSUE THREAD

**Issue by spirit93** [havardh/javaflow#79]
Need some option for mark field as nullable. And after javaflow get something like this:
```
export type Document = {
  id: number,
  person: Person,
};

export type Person = {
  id: number,
  documentSet: Array<Document>,
  someNullableField: ?string,
};
```

**Comment by havardh** [comment]
@spirit93 This is done by adding a `Nullable` annotation to the field. I've updated documentation and tests to make this more clear now.

See [Test](https://github.com/havardh/javaflow/commit/392188a5d28124e6e8df924bb7c58d0eff99108b#diff-d1009bad5a47e76d1a21c3fdb344397fR211) and [Fixture](https://github.com/havardh/javaflow/blob/392188a5d28124e6e8df924bb7c58d0eff99108b/src/test/java/com/github/havardh/javaflow/model/ModelWithNullableField.java).

Please let me know if this is sufficient for your use case. :v:
